### ISSUE TITLE
Could you explain the the correct format of the input file?

### ISSUE THREAD

**Issue by Junshuai-Song** [vals/SdA#1]
Hello,

I'm trying to get your open source code about Sda on github. 
(Https://github.com/vals/SdA)
But I don't know the correct format of input data.

I create a csv file like this:
    1,1,1,1,1
    2,2,2,2,2
    3,3,3,3,3

But it does not seem to be recognized.

Could you please send me a correct input file?

Thanks very much!

**Comment by vals** [comment]
Hi,

I looked at the file reader, which uses Pandas read_table, this reads TAB-separated files: https://github.com/vals/SdA/blob/master/sda/utils.py#L47

Just change the `,` to TAB characters in your file and it should work.
