### ISSUE TITLE
About needs for a finetuning function

### ISSUE THREAD

**Issue by SangwooLee2** [vals/SdA#3]
Hello. Could I ask you a couple of questions about your codes, please?

In your readme.md, you said that 'you took the codes from http://deeplearning.net/tutorial/ and then modified them'. At http://deeplearning.net/tutorial/SdA.html#sda, the authors defined not only pretraining_functions(), but also build_finetune_functions(). Your codes seem to have only pretraining_functions().

- Is it OK not to run  build_finetune_functions()?
- Can you suggest a way to include build_finetune_functions() in your SDA_script.py, please?

Thank you.

**Comment by vals** [comment]
This is very old code, using a deprecated software library and outdated notions of autoencoders. I would suggest looking for more recent resources to learn about autoencoders.
